spring:
  application:
    name: ms-notification
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
springdoc:
  swagger-ui:
    path: /api-docs
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: -1