spring.application.name=ms-coaches
# Puerto de ejecuci�n
server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
# Configuraci�n de base de datos MySQL
# Aseg�rate de que la base de datos 'db_Entrenador' est� creada en tu MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/db_coaches?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Dialecto y estrategia de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'none' o 'validate' es correcto cuando usas Flyway para no interferir con las migraciones
spring.jpa.hibernate.ddl-auto=none

# Configuraci�n de Logs y SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=always

# Configuraci�n de Flyway Migration
spring.flyway.enabled=true
# Esto permite que Flyway cree la tabla de historia si es la primera vez que se ejecuta
spring.flyway.baseline-on-migrate=true

springdoc.swagger-ui.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.defaultModelsExpandDepth=-1